### ISSUE TITLE
[Chests Anywhere] crash when player clicks unavailable backpack slot

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/StardewMods#45]
**Imported from Pathoschild/ChestsAnywhere#3. Original date: 2016-10-06 05:36 UTC.**
<hr />

If a player doesn't have the full backpack, some slots are unavailable and grayed out:
![sample inventory](https://cloud.githubusercontent.com/assets/230581/22624002/d3efef9c-eb3b-11e6-9417-b973e4b75258.png)

Clicking one of the disabled slots crashes the game:

```
An error occured in the base update loop: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at ChestsAnywhere.Components.ChestWithInventory.receiveLeftClick(Int32 x, Int32 y, Boolean playSound)
   at ChestsAnywhere.Components.AccessChestMenu.receiveLeftClick(Int32 x, Int32 y, Boolean playSound)
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime) in C:\Users\tomc\Documents\Visual Studio 2010\Projects\Stardew.XNA\Farmer\Farmer\Game1.cs:line 1829
   at StardewValley.Game1.Update(GameTime gameTime) in C:\Users\tomc\Documents\Visual Studio 2010\Projects\Stardew.XNA\Farmer\Farmer\Game1.cs:line 1568
   at StardewModdingAPI.Inheritance.SGame.Update(GameTime gameTime)
```

This bug has been around since 1.0.

Reported by several users: [2016-10-05 anonymouseling via Nexus comment](http://www.nexusmods.com/stardewvalley/mods/518), [2016-10-08 Bainon via Nexus bug](http://www.nexusmods.com/stardewvalley/mods/518), and [2016-10-08 Littlegal2016 via forums](http://community.playstarbound.com/threads/smapi-chests-anywhere.122603/page-3#post-3039976).

**Comment by Pathoschild** [comment]
**Imported from Pathoschild/ChestsAnywhere#3. Original date: 2016-10-07 00:26 UTC.**
<hr />

Fixed in the upcoming 1.5 release.
